name: sicode
favicon: null
layout_spectrum: 0.20264
typography_spectrum: 0.24048260180279613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfdde0'
    - '#146b7f'
    - '#68707d'
    - '#3e3e3e'
    - '#29b2ae'
  brandStrength: 0.125
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
